export default [
    {
        id: 'section1',
        sectionName: 'shareables',
        sectionItems: [
            {
                id: 'share1',
                title: 'mozzarella sticks',
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                ingredients: [
                    'mozzarella cheese',
                    'flour',
                    'bread crumbs',
                    'Italian seasoning',
                ],
                duration: 300,
                price: 6.99,
                itemThumbImg: require('/src/assets/imgs/side/side-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-1-main.jpg'),
                imgCredit: 'fried-mozzarella-sticks-shameel-mukkath'
            },
            {
                id: 'share2',
                title: 'jalapeno poppers',
                ingredients: [
                    'jalapenos',
                    'cheese',
                    'bacon',
                    'bread crumbs',
                    'garlic',
                    'chives',
                    'onions'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 8.99,
                itemThumbImg: require('/src/assets/imgs/side/side-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-2-main.jpg'),
                imgCredit: 'crispy-deep-fried-jalapeno-peppers-jayce-lab'
            },
            {
                id: 'share3',
                title: 'calamari',
                ingredients: [
                    'calamari',
                    'flour',
                    'paprika',
                    'black pepper',
                    'buttermilk',
                    'cornstach',
                    'salt',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 11.99,
                itemThumbImg: require('/src/assets/imgs/side/side-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-3-main.jpg'),
                imgCredit: 'fried-calamri-with-lemon-wedge-shameel-mukkath'
            },
            {
                id: 'share4',
                title: 'chicken wings',
                ingredients: [
                    'chicken wings',
                    'flour',
                    'paprika',
                    'garlic',
                    'hot sauce',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 13.99,
                itemThumbImg: require('/src/assets/imgs/side/side-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-4-main.jpg'),
                imgCredit: 'crispy-fried-chicken-wings-pixabay'
            },
            {
                id: 'share5',
                title: 'garlic bread',
                ingredients: [
                    'bread',
                    'garlic',
                    'butter',
                    'flour',
                    'salt',
                    'pepper',
                    'cheese',
                    'parsley',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/side/side-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-5-main.jpg'),
                imgCredit: 'garlic-bread-in-a-plate-arian-fernandez'
            },
            {
                id: 'share6',
                title: 'stuffed mushrooms',
                ingredients: [
                    'mushrooms',
                    'bread crumbs',
                    'cheese',
                    'garlic',
                    'onion',
                    'shallots',
                    'herbs',
                    'olive oil',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 9.99,
                itemThumbImg: require('/src/assets/imgs/side/side-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-6-main.jpg'),
                imgCredit: 'plate-of-stuffed-mushrooms-djordje-vezilic'
            },
            {
                id: 'share7',
                title: 'onion rings',
                ingredients: [
                    'onions',
                    'flour',
                    'vegetable oil',
                    'seasoning',
                    'eggs',
                    'bread crumbs',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/side/side-7-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-7-main.jpg'),
                imgCredit: 'fried-onion-rings-ron-lach'
            },
            {
                id: 'share8',
                title: 'potato wedges',
                ingredients: [
                    'potatoes',
                    'oil',
                    'salt',
                    'seasoning',
                    'garlic',
                    'onion',
                    'paprika',
                    'oregano',
                    'rosemary',
                    'black pepper',
                    'bread crumbs',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 7.99,
                itemThumbImg: require('/src/assets/imgs/side/side-8-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-8-main.jpg'),
                imgCredit: 'potato-wedges-in-paper-cup-georgiana-mirela'
            },
            {
                id: 'share9',
                title: 'french fries',
                ingredients: [
                    'potato',
                    'oil',
                    'salt',
                    'paprika',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/side/side-9-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-9-main.jpg'),
                imgCredit: 'french-fries-in-white-bowl-dzenina-lukac'
            },
            {
                id: 'share10',
                title: 'popcorn',
                ingredients: [
                    'popcorn kernels',
                    'butter',
                    'salt',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 2.99,
                itemThumbImg: require('/src/assets/imgs/side/side-10-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-10-main.jpg'),
                imgCredit: 'popcorn-in-ceramic-bowl-mo-abrahim'
            },

        ],
        sectionImg: ''
    },
    {
        id: 'section2',
        sectionName: 'pizzas',
        sectionItems: [
            {
                id: 'pizza1',
                title: 'margherita pizza',
                ingredients: [
                    'tomato suace', 
                    'fresh mozarella', 
                    'basil', 
                    'extra virgin oil', 
                    'pizza dough'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 15.53,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-1-main.jpg'),
                imgCredit: 'margherita-pizza-kampus-production'
            },
            {
                id: 'pizza2',
                title: 'pepperoni pizza',
                ingredients: [
                    'pepperoni', 
                    'tomato sauce', 
                    'pizza dough', 
                    'mozzarella cheese'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 12.38,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-2-main.jpg'),
                imgCredit: 'pepperoni-pizza-on-brown-wooden-table-victor-miyata'
            },
            {
                id: 'pizza3',
                title: 'BBQ chicken pizza',
                ingredients: [
                    'BBQ sauce', 
                    'grilled chicken', 
                    'mozzarella pearls', 
                    'gouda cheese', 
                    'onions', 
                    'peppers', 
                    'cilantro', 
                    'mushrooms', 
                    'Worcestershire sauce'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 17.46,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-3-main.jpg'),
                imgCredit: 'bbq-chicken-pizza-connor-mcmanus'
            },
            {
                id: 'pizza4',
                title: 'hawaiian pizza',
                ingredients: [
                    'pizza dough', 
                    'tomato sauce', 
                    'mozzarella cheese', 
                    'sliced ham', 
                    'pineapple', 
                    'bacon', 
                    'red onion', 
                    'green pepper'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 14.95,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-4-main.jpg'),
                imgCredit: 'hawaiian-pizza-amit-fulwaria'
            },
            {
                id: 'pizza5',
                title: 'veggie pizza',
                ingredients: [
                    'pizza dough', 
                    'tomato sauce', 
                    'mozzarella cheese', 
                    'bell peppers', 
                    'mushrooms', 
                    'onions', 
                    'tomatoes', 
                    'black olives', 
                    'spinach', 
                    'roasted red peppers', 
                    'artichoke hearts'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 15.49,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-5-main.jpg'),
                imgCredit: 'vegetable-pizza-engin-akyurt'
            },
            {
                id: 'pizza6',
                title: 'meat lovers pizza',
                ingredients: [
                    'tomato sauce', 
                    'pizza dough', 
                    'mozzarella cheese', 
                    'seasoned pork', 
                    'pepperoni', 
                    'italian sausage', 
                    'bacon', 
                    'ham', 
                    'beef', 
                    'salami', 
                    'canadian bacon'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 16.99,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-6-main.jpg'),
                imgCredit: 'meat-lovers-pizza-brett-jordan'
            },
            {
                id: 'pizza7',
                title: 'white pizza',
                ingredients: [
                    'pizza dough', 
                    'olive oil', 
                    'garlic', 
                    'parmesan cheese', 
                    'ricotta', 
                    'mozzarella cheese', 
                    'spinach', 
                    'tomato', 
                    'mushrooms', 
                    'leeks', 
                    'lemon zest', 
                    'fresh thyme'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 17.23,
                itemThumbImg: require('/src/assets/imgs/pizza/pizza-7-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/pizza/pizza-7-main.jpg'),
                imgCredit: 'white-pizza-polina-tankilevitch'
            },
        ],
        sectionImg: ''
    },
    {
        id: 'section3',
        sectionName: 'sandwiches',
        sectionItems: [
            {
                id: 'sandwich1',
                title: 'meatball sub',
                ingredients: [
                    'ground beef meat ball', 
                    'breadcrumbs', 
                    'eggs', 
                    'parmesan cheese', 
                    'provolone cheese', 
                    'romano cheese', 
                    'eggs', 
                    'onion', 
                    'garlic', 
                    'parsley', 
                    'marinara sauce'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 12.95,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-1-main.jpg'),
                imgCredit: 'meatball-sub-on-wooden-chopping-board-rajesh-tp'
            },
            {
                id: 'sandwich2',
                title: 'grilled cheese',
                ingredients: [
                    'sharp cheddar', 
                    'american cheese', 
                    'gruyere', 
                    'texas toast', 
                    'butter', 
                    'italian herbs'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 8.39,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-2-main.jpg'),
                imgCredit: 'person-holding-grilled-cheese-sandwiches-anthony-rahayel'
            },
            {
                id: 'sandwich3',
                title: 'BLT',
                ingredients: [
                    'bacon', 
                    'lettuce', 
                    'tomato', 
                    'bread', 
                    'mayonaise', 
                    'garlic', 
                    'basil', 
                    'lemon zest'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 6.83,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-3-main.jpg'),
                imgCredit: 'blt-sandwich-on-plate-with-potato-wedges-malcolm-garret'
            },
            {
                id: 'sandwich4',
                title: 'ham and cheese',
                ingredients: [
                    'sourdough bread', 
                    'ham', 
                    'american cheese', 
                    'guryere', 
                    'lettuce', 
                    'tomato', 
                    'onion', 
                    'pickle', 
                    'spinach', 
                    'arugula', 
                    'roasted pepper'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 9.34,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-4-main.jpg'),
                imgCredit: 'closeup-of-ham-and-cheese-sandwich-vinícius-caricatte'
            },
            {
                id: 'sandwich5',
                title: 'hot dog',
                ingredients: [
                    'hot dog', 
                    'bread'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 1.50,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-5-main.jpg'),
                imgCredit: 'four-hotdogs-on-a-black-patter-caleb-oquendo'
            },
            {
                id: 'sandwich6',
                title: 'hamburger',
                ingredients: [
                    'egg', 
                    'salt', 
                    'black pepper', 
                    'ground beef', 
                    'bread crumbs', 
                    'lettuce', 
                    'onion', 
                    'bread'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 6.51,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-6-main.jpg'),
                imgCredit: 'hamburger-andra'
            },
            {
                id: 'sandwich7',
                title: 'cheeseburger',
                ingredients: [
                    'egg', 
                    'salt', 
                    'black pepper', 
                    'ground beef', 
                    'bread crumbs', 
                    'lettuce', 
                    'onion', 
                    'bread', 
                    'american chese'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 7.23,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-7-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-7-main.jpg'),
                imgCredit: 'cheeseburger-valeria-boltneva'
            },
            {
                id: 'sandwich8',
                title: 'veggie burger',
                ingredients: [
                    'black beans', 
                    'chickpeas', 
                    'quinoa', 
                    'carrot', 
                    'mushroom', 
                    'onion', 
                    'beet', 
                    'bell pepper', 
                    'bread'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 6.58,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-8-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-8-main.jpg'),
                imgCredit: 'veggie-burger-grooveland-designs'
            },
            {
                id: 'sandwich9',
                title: 'grilled chicken',
                ingredients: [
                    'grilled chicken', 
                    'salt', 
                    'pepper', 
                    'garlic', 
                    'onion', 
                    'olive oil', 
                    'lettuce', 
                    'tomato', 
                    'bacon', 
                    'pickle', 
                    'swiss cheese'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 7.99,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-9-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-9-main.jpg'),
                imgCredit: 'chicken-sandwich-on-wood-platter-jonatan-torres'
            },
            {
                id: 'sandwich10',
                title: 'tuna melt',
                ingredients: [
                    'tuna', 
                    'mayonaise', 
                    'celery', 
                    'onion', 
                    'american cheese', 
                    'bread', 
                    'pickle relish', 
                    'capers', 
                    'mustard', 
                    'parsley', 
                    'lemon juice', 
                    'salt', 
                    'pepper'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 300,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/sandwich/sandwich-10-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/sandwich/sandwich-10-main.jpg'),
                imgCredit: 'person-holding-tuna-melt-sandwich-nano-erdozain'
            },
        ],
        sectionImg: ''
    },
    {
        id: 'section4',
        sectionName: 'sides',
        sectionItems: [
            {
                id: 'side1',
                title: 'mozzarella sticks',
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                ingredients: [
                    'mozzarella cheese',
                    'flour',
                    'bread crumbs',
                    'Italian seasoning',
                ],
                duration: 250,
                price: 3.99,
                itemThumbImg: require('/src/assets/imgs/side/side-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-1-main.jpg'),
                imgCredit: 'fried-mozzarella-sticks-shameel-mukkath'
            },
            {
                id: 'side2',
                title: 'jalapeno poppers',
                ingredients: [
                    'jalapenos',
                    'cheese',
                    'bacon',
                    'bread crumbs',
                    'garlic',
                    'chives',
                    'onions'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/side/side-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-2-main.jpg'),
                imgCredit: 'crispy-deep-fried-jalapeno-peppers-jayce-lab'
            },
            {
                id: 'side3',
                title: 'calamari',
                ingredients: [
                    'calamari',
                    'flour',
                    'paprika',
                    'black pepper',
                    'buttermilk',
                    'cornstach',
                    'salt',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 8.99,
                itemThumbImg: require('/src/assets/imgs/side/side-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-3-main.jpg'),
                imgCredit: 'fried-calamri-with-lemon-wedge-shameel-mukkath'
            },
            {
                id: 'side4',
                title: 'chicken wings',
                ingredients: [
                    'chicken wings',
                    'flour',
                    'paprika',
                    'garlic',
                    'hot sauce',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 10.99,
                itemThumbImg: require('/src/assets/imgs/side/side-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-4-main.jpg'),
                imgCredit: 'crispy-fried-chicken-wings-pixabay'
            },
            {
                id: 'side5',
                title: 'garlic bread',
                ingredients: [
                    'bread',
                    'garlic',
                    'butter',
                    'flour',
                    'salt',
                    'pepper',
                    'cheese',
                    'parsley',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 2.99,
                itemThumbImg: require('/src/assets/imgs/side/side-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-5-main.jpg'),
                imgCredit: 'garlic-bread-in-a-plate-arian-fernandez'
            },
            {
                id: 'side6',
                title: 'stuffed mushrooms',
                ingredients: [
                    'mushrooms',
                    'bread crumbs',
                    'cheese',
                    'garlic',
                    'onion',
                    'shallots',
                    'herbs',
                    'olive oil',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 7.99,
                itemThumbImg: require('/src/assets/imgs/side/side-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-6-main.jpg'),
                imgCredit: 'plate-of-stuffed-mushrooms-djordje-vezilic'
            },
            {
                id: 'side7',
                title: 'onion rings',
                ingredients: [
                    'onions',
                    'flour',
                    'vegetable oil',
                    'seasoning',
                    'eggs',
                    'bread crumbs',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 2.99,
                itemThumbImg: require('/src/assets/imgs/side/side-7-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-7-main.jpg'),
                imgCredit: 'fried-onion-rings-ron-lach'
            },
            {
                id: 'side8',
                title: 'potato wedges',
                ingredients: [
                    'potatoes',
                    'oil',
                    'salt',
                    'seasoning',
                    'garlic',
                    'onion',
                    'paprika',
                    'oregano',
                    'rosemary',
                    'black pepper',
                    'bread crumbs',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 4.99,
                itemThumbImg: require('/src/assets/imgs/side/side-8-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-8-main.jpg'),
                imgCredit: 'potato-wedges-in-paper-cup-georgiana-mirela'
            },
            {
                id: 'side9',
                title: 'french fries',
                ingredients: [
                    'potato',
                    'oil',
                    'salt',
                    'paprika',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 2.99,
                itemThumbImg: require('/src/assets/imgs/side/side-9-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-9-main.jpg'),
                imgCredit: 'french-fries-in-white-bowl-dzenina-lukac'
            },
            {
                id: 'side10',
                title: 'popcorn',
                ingredients: [
                    'popcorn kernels',
                    'butter',
                    'salt',
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 1.05,
                itemThumbImg: require('/src/assets/imgs/side/side-10-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/side/side-10-main.jpg'),
                imgCredit: 'popcorn-in-ceramic-bowl-mo-abrahim'
            },
        ],
        sectionImg: ''
    },
    {
        id: 'section5',
        sectionName: 'desserts',
        sectionItems: [
            {
                id: 'dessert1',
                title: 'cheesecake',
                ingredients: [
                    'cheesecake',
                    'egg',
                    'sugar',
                    'sour cream',
                    'vanilla extract',
                    'lemon juice',
                    'flour'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 5.95,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-1-main.jpg'),
                imgCredit: 'slice-of-cheesecake-wendy-wei'
            },
            {
                id: 'dessert2',
                title: 'brownie',
                ingredients: [
                    'chocolate', 
                    'butter', 
                    'sugar', 
                    'egg', 
                    'flour', 
                    'vanilla extract', 
                    'baking powder', 
                    'salt'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 4.87,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-2-main.jpg'),
                imgCredit: 'chocolate-brownie-cake-veersajid'
            },
            {
                id: 'dessert3',
                title: 'vanilla cake',
                ingredients: [
                    'butter', 
                    'flour', 
                    'egg', 
                    'sugar', 
                    'vanilla extract', 
                    'milk', 
                    'baking powder', 
                    'salt'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 4.51,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-3-main.jpg'),
                imgCredit: 'slice-of-dessert-cake-on-white-plate-ionela-mat'
            },
            {
                id: 'dessert4',
                title: 'cannoli',
                ingredients: [
                    'flour', 
                    'egg', 
                    'butter', 
                    'sugar', 
                    'marsala wine', 
                    'ricotta cheese', 
                    'chocolate chips', 
                    'vanilla extract', 
                    'cinnamon', 
                    'orange zest'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 3.75,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-4-main.jpg'),
                imgCredit: 'three-cannolis-on-a-black-plate-valeria-boltneva'
            },
            {
                id: 'dessert5',
                title: 'chocolate chip cookie',
                ingredients: [
                    'butter', 
                    'egg', 
                    'brown sugar', 
                    'sugar', 
                    'baking soda', 
                    'vanilla extract', 
                    'salt', 
                    'chocolate chips'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 2.81,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-5-main.jpg'),
                imgCredit: 'closeup-of-three-chocolate-chip-cookies-lisa-fotios'
            },
            {
                id: 'dessert6',
                title: 'cinnamon roll',
                ingredients: [
                    'flour', 
                    'sugar', 
                    'butter', 
                    'milk', 
                    'egg', 
                    'cinnamon', 
                    'yeast', 
                    'cream cheese'
                ],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 250,
                price: 3.46,
                itemThumbImg: require('/src/assets/imgs/dessert/dessert-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/dessert/dessert-6-main.jpg'),
                imgCredit: 'cinnamon-roll-on-plate-pixabay'
            },
        ],
        sectionImg: ''
    },
    {
        id: 'section6',
        sectionName: 'drinks',
        sectionItems: [
            {
                id: 'drink1',
                title: 'beer',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 5.99,
                itemThumbImg: require('/src/assets/imgs/drink/drink-1-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-1-main.jpg'),
                imgCredit: 'beer-filled-mug-on-table-engin-akyurt'
            },
            {
                id: 'drink2',
                title: 'wine',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 7.99,
                itemThumbImg: require('/src/assets/imgs/drink/drink-2-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-2-main.jpg'),
                imgCredit: 'wine-glasses-valeria-boltneva'
            },
            {
                id: 'drink3',
                title: 'soda',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 1.52,
                itemThumbImg: require('/src/assets/imgs/drink/drink-3-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-3-main.jpg'),
                imgCredit: 'photo-of-soda-cans-sebastian-coman-photography'
            },
            {
                id: 'drink4',
                title: 'iced tea',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 2.51,
                itemThumbImg: require('/src/assets/imgs/drink/drink-4-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-4-main.jpg'),
                imgCredit: 'iced-tea-with-lemon-slices-shameel-mukkath'
            },
            {
                id: 'drink5',
                title: 'coffee',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 2.99,
                itemThumbImg: require('/src/assets/imgs/drink/drink-5-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-5-main.jpg'),
                imgCredit: 'person-pouring-creamer-in-coffee-chevanon-photography'
            },
            {
                id: 'drink6',
                title: 'lemonade',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 1.68,
                itemThumbImg: require('/src/assets/imgs/drink/drink-6-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-6-main.jpg'),
                imgCredit: 'glass-of-lemon-juice-rimmed-with-sugar-and-garnished-with-lemon-and-mint-designbyja'
            },
            {
                id: 'drink7',
                title: 'sparkling water',
                ingredients: [],
                description: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
                duration: 100,
                price: 1.87,
                itemThumbImg: require('/src/assets/imgs/drink/drink-7-thumb.jpg'),
                itemMainImg: require('/src/assets/imgs/drink/drink-7-main.jpg'),
                imgCredit: 'glass-of-sparkling-water-with-lime-in-it-dan-gold'
            },
        ],
        sectionImg: ''
    },
    {
        id: 'section7',
        sectionName: 'toppings',
        sectionItems: [
            {
                id: 'topping1',
                title: 'bacon',
                ingredients: [],
                description: '',
                duration: 150,
                price: 2.40,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping2',
                title: 'basil',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.78,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping3',
                title: 'BBQ sauce',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.50,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping4',
                title: 'buffalo suace',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.50,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping5',
                title: 'cheese',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.80,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping6',
                title: 'chive',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.50,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping7',
                title: 'fired egg',
                ingredients: [],
                description: '',
                duration: 150,
                price: 2.20,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping8',
                title: 'garlic',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.48,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping9',
                title: 'green pepper',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.73,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping10',
                title: 'ham',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.90,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping11',
                title: 'hashbrown',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.50,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping12',
                title: 'ketchup',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.25,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping13',
                title: 'mayo',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.25,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping14',
                title: 'melted cheddar',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.60,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping15',
                title: 'mushroom',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.20,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping16',
                title: 'mustard',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.25,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping17',
                title: 'olive',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.98,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping18',
                title: 'onion',
                ingredients: [],
                description: '',
                duration: 0,
                price: 0.35,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping19',
                title: 'pepporoni',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.20,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping20',
                title: 'potato sticks',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.60,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping21',
                title: 'proschiuto',
                ingredients: [],
                description: '',
                duration: 150,
                price: 2.80,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping22',
                title: 'red pepper',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.73,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping23',
                title: 'relish',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.50,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping24',
                title: 'salami',
                ingredients: [],
                description: '',
                duration: 150,
                price: 1.40,
                itemImg: '',
                imgCredit: ''
            },
            {
                id: 'topping25',
                title: 'special sauce',
                ingredients: [],
                description: '',
                duration: 150,
                price: 0.30,
                itemImg: '',
                imgCredit: ''
            },
        ],
        sectionImg: ''
    },
]